### ISSUE TITLE
textsim.py中未定义变量self.__collate_fn，运行报错。

### ISSUE THREAD

**Issue by BeyondLightYear** [DataArk/CHIP2021-Task3#1]
你好，运行textsim.py时报错，经检查代码，发现第94行使用了变量self.__collate_fn，但该变量却没用定义。
<img width="556" alt="234" src="https://user-images.githubusercontent.com/52820978/149076492-cdc6058e-f774-4b5a-aaed-a992b3714993.png">
当我去掉该参数进行训练时，出现了新错误：
<img width="557" alt="789" src="https://user-images.githubusercontent.com/52820978/149077066-66995588-8864-4274-990c-21275abc6687.png">

我该怎么办呢？敬请大佬拯救，谢谢。

**Comment by BeyondLightYear** [comment]
感谢大神 
报错原因：安装了最新版本的ark-nlp，新版本不向下兼容
解决：pip install ark-nlp==0.0.2

**Comment by heng3366** [comment]
> 感谢大神 报错原因：安装了最新版本的ark-nlp，新版本不向下兼容 解决：pip install ark-nlp==0.0.2
我复现第一步elastic search就遇到问题了，请问你知道原因吗，出错如下
PUT http://localhost:5601/icd_diagnose_test_20210601 [status:404 request:0.025s]
PUT http://localhost:5601/icd_diagnose_test_20210601 [status:404 request:0.024s]
Traceback (most recent call last):
  File "es_index.py", line 35, in <module>
    result = es_client.indices.create(index='icd_diagnose_test_20210601', body=index_, ignore=400)
  File "/home/ai998/.conda/envs/torch/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/ai998/.conda/envs/torch/lib/python3.8/site-packages/elasticsearch/client/indices.py", line 90, in create
    return self.transport.perform_request('PUT', _make_path(index),
  File "/home/ai998/.conda/envs/torch/lib/python3.8/site-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/home/ai998/.conda/envs/torch/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 161, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/ai998/.conda/envs/torch/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: <exception str() failed>

**Comment by heng3366** [comment]
> 感谢大神 报错原因：安装了最新版本的ark-nlp，新版本不向下兼容 解决：pip install ark-nlp==0.0.2
我复现第一步elastic search就遇到问题了，请问你知道原因吗，出错如下
PUT http://localhost:5601/icd_diagnose_test_20210601 [status:404 request:0.025s]
PUT http://localhost:5601/icd_diagnose_test_20210601 [status:404 request:0.024s]
Traceback (most recent call last):
  File "es_index.py", line 35, in <module>
    result = es_client.indices.create(index='icd_diagnose_test_20210601', body=index_, ignore=400)
  File "/home/ai998/.conda/envs/torch/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/ai998/.conda/envs/torch/lib/python3.8/site-packages/elasticsearch/client/indices.py", line 90, in create
    return self.transport.perform_request('PUT', _make_path(index),
  File "/home/ai998/.conda/envs/torch/lib/python3.8/site-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/home/ai998/.conda/envs/torch/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 161, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/ai998/.conda/envs/torch/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: <exception str() failed>
